spring.application.name=wallet-payment-platform
spring.datasource.url=jdbc:postgresql://localhost:5432/walletplatform
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.threads.virtual.enabled=true