spring.application.name=wallet-payment-platform
spring.datasource.url=jdbc:postgresql://localhost:5432/walletplatform
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.threads.virtual.enabled=true
# ===================================================================
# Kafka Bootstrap Server
# ===================================================================
# Use localhost:9094 if Spring Boot is running directly on your host machine.
# Use kafka:9092 if Spring Boot is also containerized in the same Docker network.
spring.kafka.bootstrap-servers=localhost:9094
# ===================================================================
# Producer Configuration
# ===================================================================
# Serializer class for keys (String is standard)
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
# Serializer class for values (StringSerializer or JsonSerializer)
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
# Acknowledgment level: 'all' (or '-1') guarantees message durability
spring.kafka.producer.acks=all
# Number of retries on send failure
spring.kafka.producer.retries=3
# Enable idempotence to prevent duplicate messages on retries
spring.kafka.producer.properties.enable.idempotence=true
# Consumer Settings
spring.kafka.consumer.group-id=transfer-group
spring.kafka.consumer.auto-offset-reset=earliest
# Serialization Settings
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
# 1. Disable Kafka's native background auto-commit thread
spring.kafka.consumer.enable-auto-commit=false
# 2. Tell Spring Boot that you will manually control when offsets are committed
# MANUAL_IMMEDIATE commits the offset synchronously to Kafka as soon as your code calls ack.acknowledge()
spring.kafka.listener.ack-mode=manual_immediate